### ISSUE TITLE
你好，请问你有实现vlog的GC吗？

### ISSUE THREAD

**Issue by ravenxrz** [coyorkdow/wisckey#7]
如题。

**Comment by coyorkdow** [comment]
目前还没有，因为naive的gc机制和snapshot功能不兼容。

**Comment by ravenxrz** [comment]
哦哦，了解了。简单看了下代码，目前的做法是当vlog size达到一定预定值就切换新的vlog哈。



---原始邮件---
发件人: "youtao ***@***.***&gt;
发送时间: 2021年12月21日(周二) 中午11:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [coyorkdow/wisckey] 你好，请问你有实现vlog的GC吗？ (Issue #7)




 
目前还没有，因为naive的gc机制和snapshot功能不兼容。
